name: Deploy Quiz App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest
      
    - name: Run Docker container
      run: docker run -d --name quiz-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest

    - name: Show running containers
      run: docker ps
